Cloned page delivery returns from the footer pages
hlxsites/asprey pull request #79
Opened 2023-09-18 10:07 UTC by vlajoaga

## Description
Cloned the delivery returns page from the footer pages.

Blocks location: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BEF278BC0-8FAC-4960-8576-4357FD54DF35%7D&file=delivery-return.docx&action=default&mobileredirect=true

Fix #57

## Test URLs:
- Before: https://main--asprey--hlxsites.hlx.page/gb/en/delivery-return
- After: https://issue-57--asprey--hlxsites.hlx.page/gb/en/delivery-return

2023-09-18 12:39 UTC, herzog31 reviewed
Looks great for your first PR :) 

Could you please also have a look at the mobile version of the page?

Original: 
![image](https://github.com/hlxsites/asprey/assets/4084418/44630739-6ce6-42e8-b4c3-0c6e998e69bc)

Franklin:
![image](https://github.com/hlxsites/asprey/assets/4084418/bda6b882-b572-440d-b7e8-1ab31de37cbe)

2023-09-18 12:39 UTC, herzog31 commented on blocks/goods-table/goods-table.css
> +    font-family: Muli,-apple-system,BlinkMacSystemFont,sans-serif;
Please use variables for fonts and colours wherever you use them in your PR.

https://github.com/hlxsites/asprey/blob/main/styles/styles.css#L15-L64

2023-09-18 12:39 UTC, herzog31 commented on blocks/goods-table/goods-table.css
> +.goods-table {
Let's call this block `table`, so it's re-useable across the whole page.

You can add specific styling by adding a class in brackets behind the block name, e.g. `Table (goods)`. You can use this class then to add all styling that is specific to the delivery and returns page.

2023-09-18 12:39 UTC, herzog31 commented on blocks/left-navigation-list/left-navigation-list.css
> +  .left-navigation-list {
Let's call this block `side-navigation`. In the Word document you can refer to it as `Side Navigation`.

2023-09-18 12:39 UTC, herzog31 commented on blocks/left-navigation-list/left-navigation-list.css
> +    text-align: left!important;
Do you need this in this block? I don't see anywhere in the upper CSS hierarchy a rule that sets this so something else than `left`.

2023-09-18 12:39 UTC, herzog31 commented on styles/side-navigation.css
> +*data-default-content-wrapper{
Do you still need this file?

2023-09-18 12:39 UTC, herzog31 commented on blocks/right-navigation-content/right-navigation-content.css
> +.block.right-navigation-content {
Since the content is in another file, you can remove all `right-navigation-content` files.

2023-09-18 12:39 UTC, herzog31 commented on scripts/scripts.js
> +  const contentBlocks = Array.from(sectionElements.children);
I would rather do something like this:

```javascript
// Find navigation and remove it
const navigation = section.querySelector('.left-navigation-list')
section.removeChild(navigation);

// Move all content into its own div
const contentContainer = document.createElement('div');
Array.from(section.children).forEach((elem) => contentContainer.appendChild(elem));

// Style the content
contentContainer.classList.add('side-navigation-content');

// Re-add both containers
section.appendChild(navigation);
section.appendChild(contentContainer);
```

2023-09-18 12:39 UTC, herzog31 commented on scripts/scripts.js
> +        pElement.classList.add('right-navigation-content-p');
I recommend to add a class to the content container element instead of every element inside. There might be elements in the content you don't anticipate in this code.

2023-09-18 12:39 UTC, herzog31 commented on scripts/scripts.js
> +  const sectionElements = main.querySelector('.delivery-return-side-navigation');
Could you call this style something a bit more generic? It will be used for the other pages with the same structure as well. e.g. (`side-navigation-content`).

2023-09-18 12:39 UTC, herzog31 commented on styles/styles.css
> +.default-content-wrapper-wrapper {
This applies to all content on all pages. Should this be rather scoped to this page like the other rules?

2023-09-18 18:29 UTC, vlajoaga commented on scripts/scripts.js
> +  const sectionElements = main.querySelector('.delivery-return-side-navigation');
Understood, it will be reusable.

2023-09-18 18:59 UTC, vlajoaga commented on scripts/scripts.js
> +  const contentBlocks = Array.from(sectionElements.children);
This was my first approach also, but I had problems removing the child, now I realised the child is the wrapper of the div, and not the left navigation div itself.

2023-09-18 18:59 UTC, vlajoaga commented on scripts/scripts.js
> +        pElement.classList.add('right-navigation-content-p');
Fixed by adding to the code above: contentContainer.classList.add('right-navigation-content');

2023-09-19 14:29 UTC, herzog31 approved these changes

2023-09-25 09:59 UTC, hannessolo requested changes

2023-09-25 09:59 UTC, hannessolo commented on styles/styles.css
> +  margin-left: 19.3333%;
On my screen size (1440x900 effective) this pushes the content much further right than on the current page. 

Your version:

<img width="600" alt="Screenshot 2023-09-25 at 11 56 58" src="https://github.com/hlxsites/asprey/assets/24207564/7ab330f9-9c23-41d4-b480-babe110f1931">


Real version: 

<img width="600" alt="Screenshot 2023-09-25 at 11 57 20" src="https://github.com/hlxsites/asprey/assets/24207564/edc03522-fb7c-4da1-80b8-2a43a731496f">

2023-09-25 09:59 UTC, hannessolo commented on scripts/scripts.js
> +  const section = main.querySelector('.side-navigation-content');
Instead of needing extra section metadata, could we auto-detect which sections have a `Side Navigation` block in them, and then add this section metadata automatically? 

This could make it easier for authors.

2023-09-27 08:59 UTC, jckautzmann commented on scripts/scripts.js
> +  const section = main.querySelector('.side-navigation-content');
@vlajoaga @hannessolo Wouldn't it make more sense to add this code to the Side Navigation block?

2023-09-29 14:35 UTC, hannessolo commented on tools/importer/import.js
> +// TODO CV: aici Cosmin
remove todo?

2023-09-29 14:36 UTC, hannessolo commented on scripts/scripts.js
> +  const section = main.querySelector('.side-navigation-content');
@jckautzmann I thought about this too but since we are moving the section around I think it's better to keep it out of the block code

2023-09-29 14:37 UTC, hannessolo approved these changes

2023-10-02 11:26 UTC, merged