Implement Breadcrumbs
hlxsites/asprey pull request #82
Opened 2023-09-19 11:45 UTC by jckautzmann

- supports language root
- supports author based breadcrumb (defined in the page) 
- supports auto-generated breadcrumbs based on the page path -- hidden on mobile

## Description

Fix #38

## Test URLs:
- Before: https://main--asprey--hlxsites.hlx.page/gb/en
- After:
    - https://breadcrumb--asprey--hlxsites.hlx.live/gb/en

## Examples

- manual: https://breadcrumb--asprey--hlxsites.hlx.live/drafts/jkautzma/breadcrumbs/manual
- auto-generated without language root: https://breadcrumb--asprey--hlxsites.hlx.live/drafts/jkautzma/breadcrumbs/auto
- auto-generated with language root: https://breadcrumb--asprey--hlxsites.hlx.live/gb/en/men/by-category/bags-cases/bags

2023-09-19 12:22 UTC, Kronnox requested changes

2023-09-19 12:22 UTC, Kronnox commented on blocks/breadcrumb/breadcrumb.css
> +  display: flex!important;
I think your `display` properties are a bit messed up. This way it won't disappear on mobile, am I right?

2023-09-19 12:54 UTC, jckautzmann commented on blocks/breadcrumb/breadcrumb.css
> +  display: flex!important;
@Kronnox good catch! I fixed it in https://github.com/hlxsites/asprey/pull/82/commits/161daf8fd92f085d12da334224451f70e6883692

2023-09-20 09:33 UTC, Kronnox commented on blocks/breadcrumb/breadcrumb.js
> +  li.innerHTML = !isLast ? `
Even though I cannot think of any actual attack right now, I'm not a huge fan of the use of `innerHTML` here. This always leaves possibilities for injection attacks. I would rather replace this part with the creation of the DOM object via JS.

2023-09-20 11:41 UTC, herzog31 commented on blocks/breadcrumb/breadcrumb.js
> +    // eslint-disable-next-line no-await-in-loop
There is no await in the loop anymore.

2023-09-20 11:41 UTC, herzog31 commented on blocks/breadcrumb/breadcrumb.js
> +    const title = queryIndex.find((page) => page.path === path)?.title ?? segments[i];
Could you please make sure that a link is rendered only if the page is found in the query index? Otherwise it's fine to simply add the name of the page like you do it with the last item.

2023-09-20 11:41 UTC, herzog31 commented on blocks/breadcrumb/breadcrumb.js
> +  li.innerHTML = !isLast ? `
Or simply use `document.createRange().createContextualFragment`. The critical part here is the title which might be taken directly from the URL if the site is not in the index. Since the URL needs to actually exist though, the risk is minimal. If you run a regex over those to strip everything that's not `a-z-`, this should not be an issue anymore.

2023-09-20 20:50 UTC, jckautzmann commented on blocks/breadcrumb/breadcrumb.js
> +  li.innerHTML = !isLast ? `
I addressed it at https://github.com/hlxsites/asprey/pull/82/commits/587b01ea690ce91a0f0d155c99152c9b18e9c877

2023-09-20 20:51 UTC, jckautzmann commented on blocks/breadcrumb/breadcrumb.js
> +    const title = queryIndex.find((page) => page.path === path)?.title ?? segments[i];
@herzog31 Addressed at https://github.com/hlxsites/asprey/pull/82/commits/587b01ea690ce91a0f0d155c99152c9b18e9c877

2023-09-21 06:09 UTC, hannessolo approved these changes

2023-09-21 06:09 UTC, hannessolo commented on scripts/scripts.js
> +    buildBreadcrumb(main);
All looks great. Just wondering if `buildBreadcrumb` is the correct name for this function. At first glance I thought this was actually adding the block to the page, which it's not (and it shouldn't).

Maybe `addBreadcrumbPlaceholder` or something?

2023-09-21 07:41 UTC, Kronnox approved these changes

2023-09-21 09:28 UTC, jckautzmann commented on scripts/scripts.js
> +    buildBreadcrumb(main);
@hannessolo I agree that the name is misleading. I renamed it `decorateBreadcrumb` and moved it to `decorateMain(main)`. See commit  https://github.com/hlxsites/asprey/pull/82/commits/51f6f78a5dc8172d5b690158e60ca2b4beccb4aa

2023-09-21 13:34 UTC, merged